trigger: none  # Trigger only on successful builds, not on code pushes
pr: none

resources:
  pipelines:
    - pipeline: sourcePipeline
      source: 'tidalwave6.AdvSoftwareDevG3'  # Exact name of your build pipeline
      trigger:
        branches:
          include:
            - main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Deploy
  displayName: 'Deploy to Azure App Service'
  jobs:
  - deployment: DeployApp
    displayName: 'Deploy to Production'
    environment: 'Production'
    strategy:
      runOnce:
        deploy:
          steps:
          # Download the build artifact from the previous pipeline
          - download: sourcePipeline
            artifact: drop  # This should match the artifact name published in the build pipeline

          # Deploy to Azure App Service
          - task: AzureWebApp@1
            inputs:
              azureSubscription: 'AzureServiceConnection-Bookstore'  # Replace with your Azure service connection name in Azure DevOps
              appName: 'AdvSoftwareBookstore'  # Replace with the name of your Azure App Service
              package: '$(Pipeline.Workspace)/drop/online-bookstore-app.zip'
              deploymentMethod: 'auto'  # Choose between auto, run-from-package, or zip deploy
  displayName: 'Deploy to Azure App Service'
